In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('SMSSpamCollection', sep='\t', names=['label', 'message'])
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.rename(columns = {'label':'Category', 'message':'Message'}, inplace = True)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Message'],df['spam'], stratify=df['spam'])

X_train.head(4)

1752    * Was thinking about chuckin ur red green n bl...
5056    Am on a train back from northampton so i'm afr...
1563    Dude just saw a parked car with its sunroof po...
2031    Ugh y can't u just apologize, admit u were wro...
Name: Message, dtype: object

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub


In [ ]:
!pip install tensorflow-text
import tensorflow_text as text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


ImportError: ignored

In [ ]:
bert_preprocess = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3')
bert_encoder = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4')

In [ ]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"])

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8435169 , -0.51327264, -0.88845724, ..., -0.74748874,
        -0.75314736,  0.91964483],
       [-0.8720836 , -0.5054398 , -0.9444668 , ..., -0.85847515,
        -0.7174535 ,  0.88082975]], dtype=float32)>

In [ ]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [ ]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer (KerasLayer)       {'input_word_ids':   0           ['text[0][0]']                   
                                (None, 128),                                                      
                                 'input_type_ids':                                                
                                (None, 128),                                                      
                                 'input_mask': (Non                                               
                                e, 128)}                                                      

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=1, batch_size = 32)

Epoch 1/2
131/131 [==============================] - 1945s 15s/step - loss: 0.3251 - accuracy: 0.8667
Epoch 2/2
  2/131 [..............................] - ETA: 31:44 - loss: 0.2073 - accuracy: 0.9062

KeyboardInterrupt: ignored

In [ ]:
model.evaluate(X_test, y_test)

44/44 [==============================] - 676s 15s/step - loss: 0.2557 - accuracy: 0.8693


[0.25566962361335754, 0.8693467378616333]

In [ ]:
y_predicted = model.predict(X_test)
y_predicted = y_predicted.flatten()

44/44 [==============================] - 638s 14s/step


In [ ]:
print(y_predicted)

[0.30249915 0.19570409 0.24563682 ... 0.07449002 0.16547659 0.44535294]


In [ ]:
import numpy as np

y_predicted = np.where(y_predicted > 0.5, 1, 0)
y_predicted

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_predicted

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_predicted = model.predict(X_test)

44/44 [==============================] - 650s 15s/step


In [ ]:
y_predicted

array([[0.30249915],
       [0.19570409],
       [0.24563682],
       ...,
       [0.07449002],
       [0.16547659],
       [0.44535294]], dtype=float32)